### PR TITLE
Update full_code.py

### PR DESCRIPTION
**Pull request by JamesRaynor67**
Add sess.close() to the end.
It's my first time to open a pull request, if any thing I did it's wrong, please tell me. Thx

### CODE REVIEW

**Comment by MorvanZhou** [comment]
Cool, make this perfect.

**Comment by MorvanZhou** [comment]
Thank you for the update. But after my consideration, the sess.close() is not necessary code, and to keep it or not may cause some confusions to beginners as these tutorials are indeed just for beginners. So I decide to leave it as simple as it can.

**Comment by JamesRaynor67** [comment]
ok, you are the boss.
At first I thought this may cause GPU memory leak. But it seems not. Still, I modified them.



Sent from myMail for iOS


Tuesday, 25 October 2016, 17:24 +0900 from Morvan  <notifications@github.com>:

**Comment by JamesRaynor67** [comment]
Hi，看了你的一些视频觉得很不错，我现在正在东京大学读研究生，方便加个微信吗？有空来日本玩 ^_^
我的微信是 ishidabaigann

**Comment by MorvanZhou** [comment]
Hi, James,

我微信就生活圈里能见到面的朋友~ 我想生活和 python 的圈子分开.

不过我们可以加微博,如果你有的话~ 微博的留言也很方便, 而且也会 post 一些生活的东西.

http://www.weibo.com/pythontutorial

谢谢你

Morvan

**Pull request closed without merging**
